# Generated by Django 4.2.4 on 2023-09-05 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecttopic',
            options={'permissions': [('view_spmsapp_projecttopic', 'Can view project topic')]},
        ),
    ]
