# Generated by Django 4.2.4 on 2023-09-06 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import spmsapp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spmsapp', '0003_projectselection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='projecttopic',
            name='supervisor',
            field=models.ForeignKey(default=spmsapp.models.get_default_supervisor, on_delete=django.db.models.deletion.CASCADE, to='spmsapp.supervisor'),
        ),
    ]
